/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class core_JNITest */

#ifndef _Included_core_JNITest
#define _Included_core_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     core_JNITest
 * Method:    sum
 * Signature: ([DI)D
 */
JNIEXPORT jdouble JNICALL Java_core_JNITest_sum
  (JNIEnv *, jobject, jdoubleArray, jint);

#ifdef __cplusplus
}
#endif
#endif
