/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class core_JavaNativeInterface */

#ifndef _Included_core_JavaNativeInterface
#define _Included_core_JavaNativeInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     core_JavaNativeInterface
 * Method:    binToBestSplit
 * Signature: ([D[D[IIICIIID)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_core_JavaNativeInterface_binToBestSplit
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jintArray, jint, jint, jchar, jint, jint, jint, jdouble);

#ifdef __cplusplus
}
#endif
#endif
